# Generated by Django 4.0.2 on 2022-03-04 20:47

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Surname')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Id of a chat')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TelegramBot.category')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryDataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('clients', models.ManyToManyField(related_name='clients', to='TelegramBot.BotUser')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='TelegramBot.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=30)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('tags', models.CharField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TelegramBot.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=69, unique=True)),
                ('username', models.CharField(blank=True, max_length=69, null=True)),
                ('name', models.CharField(blank=True, max_length=69, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.shop')),
            ],
        ),
    ]
