# Generated by Django 4.0.2 on 2022-11-10 01:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Surname')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='Id of a chat')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('max_shops', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TelegramBot.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('welcome_message', models.TextField(blank=True, max_length=256, null=True)),
                ('clients', models.ManyToManyField(related_name='clients', to='TelegramBot.BotUser')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='TelegramBot.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryDataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, null=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='ShopAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to='TelegramBot.shop')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=30)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('tags', models.CharField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TelegramBot.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=69, unique=True)),
                ('username', models.CharField(blank=True, max_length=69, null=True)),
                ('name', models.CharField(blank=True, max_length=69, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.shop')),
            ],
        ),
    ]
