# Generated by Django 4.0.2 on 2022-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='max_shops',
            field=models.IntegerField(default=4),
        ),
    ]
