# Generated by Django 4.0.2 on 2022-03-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0002_alter_temporarydatastorage_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarydatastorage',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
