# Generated by Django 4.0.2 on 2022-03-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0003_shoppikey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopPIKey',
            new_name='ShopAPIKey',
        ),
    ]
